### ISSUE TITLE
Extract CDLs from an EDL?

### ISSUE THREAD

**Issue by dupsta** [shidarin/cdl_convert#41]
Hello friends, 
I have a bunch of EDL files.  Contained inside of these EDLs are CDL values we are after. They are all laid out, I can copy and paste them..kinda a drag. 
Does this tool allow a user to extract each CDL value inside the EDL, and save it individually as a .cdl file? This tool really sounds interesting and useful.  Got my hopes up. 
I have no experience coding, and stumbled upon this via google.  I am interested in this type of extraction, but after reading through the documentation and watching tutorials realized I would need further explanation to even begin.  Is it possible to find a user that can demo what this actual does and how it works?  
Thanks for your help and advice. 
Dupsta

**Comment by shidarin** [comment]
Hi Dupsta,

That is correct. This tool goes through an EDL if it's a supported type, and extracts and converts CDL files into the type specified.

It's purely a command line tool, no GUI. Is there a specific part you're having difficulty with? The documentation has a decent amount of examples, but I'm not sure what tutorial videos you are watching- there aren't any.

**Comment by dupsta** [comment]
Thanks again Sean,

Hope your fourth was fun and had some time off. 

Yes this sounds like a nice lil tool to kick out .cdl files.  I truly wish I was more experienced in the simplest of coding and command line procedures. 
I thought this tool could help our current workflow. I am just exploring some overall ALT workflow ideas and this looks really great. Hopes are high.  

So I started to watch python tutorial scripting videos to just get an idea what the heck I was getting involved in.  I wish I had a few days to dive further into.  I just don't.  
I don't want to give up on this CDL line command tool.  This all looks like a great time saver but this is my first time trying to use the terminal window.  

Most likely you'll use cdl_convert as a script.  YES.

Script Usage
If you just want to convert to a .cc XML file, the only required argument
is an input file, like so::

$ cdl_convert ./di_v001.flex

You can override the default .cc output, or provide multiple outputs with
the -o flag.:

$ cdl_convert ./di_v001.flex -o cc,cdl
For example I am not sure what any of this means.  LOL

If you don't want to bother with a pip style install , you can alternatively
grab the entire cdl_convert directory, then set up a shortcut to call
cdl_convert/cdl_convert.py

Sean, I downloaded the master zip CDL convert file, I am not following where to place that folder or how to proceed: Thank you for your patience.  

With some practice I can show the Editors how to break this out which will make my life easier! Yea the blind leading the blind. Lol.   
 
The goal is:
Avid kicks out an .edl. with those pesky CDL values. Assistant breaks the EDL down into multiple .cdl files and sends all those individual files to VFX. 

That my friend would be sweet!

Anthony-

**Comment by shidarin** [comment]
Hi Anthony, let's get started.

Before we get started- does your company have IT? Systems? Pipeline? If so, they should be the ones installing it. You tell them you need this program, and it needs python, and they should figure out the rest. If you're a very small operation, read on. If you DO have a systems, IT, pipeline department etc, they might get extremely upset at you if you continue though.

So, I'm guessing you're running OSX, or possibly Windows? If you were running Linux, you'd probably be familiar with the terminal already. If you're running OSX, this should be decently easy. If you're running windows, it's harder but not impossible.

So, OSX or windows?

Basically, what we need to do is:

1) Determine if python is installed correctly
In the terminal window, just type `python --version`. `python` is the name of the program we're executing. `--version` is an argument, or instruction to the program. We've instructed python to tell us what version of python is running when you type `python`. It should spit back something like `Python 2.7.5` but really, anything between 2.6 and 3.4 is fine.

Another important command line argument is '--help'. Almost every program will respond to it, and tell you what other arguments you can give to that program.

2) Determine if pip is installed correctly
If you're on a mac, installing pip is easy. If you're on a windows, installing it is easy, but actually using it is hard because there's a trick. Try typing `pip --version`. If it's installed correctly, you'll get the version back. If it's not installed correctly (or you're on windows and haven't modified the PATH (I'll explain later)), it'll spit back something about how pip isn't a recognized command.

If pip isn't installed and you're on OSX, you can install it by typing `sudo easy_install pip` and then typing in your password (if you're an admin on your computer). Windows is harder. I'm not going to cover it unless you reply saying you're on windows.

The `sudo` part is an instruction to the terminal that you want to do things with admin privledges. If commands below give you errors about privileges, try pre-pending `sudo` to them. Again, this is a good way to piss off your systems administration if you have them.

3) You don't need to install setuptools, it's part of python.

4) Installing cdl_convert.
First, uninstall it if you're already installed it. `pip uninstall cdl_convert` That calls `pip`, the program, tells it you want to `uninstall`, which is an argument, then `cdl_convert`, which is another argument. In this case, `cdl_convert` is the package you want to uninstall.

Then, we'll install. No need to download the zip file, or install via Pip. You want the latest, not what is on pip, so....
`pip install https://github.com/shidarin/cdl_convert/archive/develop.zip`

This will install the latest cdl_convert.

Now you can run cdl_convert from the command line with `cdl_convert file.edl` it will fill an output directly with a giant cdl file for the edl. 

I'm sure you have more questions, so I'll stop here and let you ask them.

**Comment by dupsta** [comment]
Sean, your a badass. Excuse the profanity...:)  
So you guessed it we are indeed, small.  IT is not interested in working with me on this, and I like to get stuff done myself to learn and be self sufficient. 
The pipeline is something I am always wanting to have certain things automated to speed through the repetitive tasks.  So I try to implement as much as I can, proactive approach.  I get frustrated knowing there's got to be something out there that is better than how we do it..Bam..enter Sean...

No one will be mad at me and this is a good thing to automate.  I love pipeline, workflow, color science, VFX, blah blah blah.... So with your help and your amazingballz write with step by step I will go through this Thurs and see where I get stuck. 
From the screen grabs I sent you last, I am on a osx which now comes with Python 2.7? and these instruction make much more since after spending days on this so far. I can wrap my head around this now.  I am pumped you have provided me some wind for these sails.  Thanks...
I will read through these instructions again tomorrow, step by step.  I write up stuff like this for others on diff subjects, but I know what a pain and how tricky it is to simplify things.  So much appreciated for taking the time to extend some knowledge and help. So cool man...

Thanks so much, I will dive into this thurs, fingers crossed.  I got this man!!!

Anthony-

Date: Tue, 7 Jul 2015 23:23:58 -0700

**Comment by shidarin** [comment]
Ahh, I totally missed your screenshots. Sorry!

If pip is already installed, all you should have to do is the last part to install cdl_convert, then figure out cdl_converts command line options to tweak it to be exactly what you want to deliver.

**Comment by dupsta** [comment]
Thanks again Sean,

I seem to maybe have a few permissions errors?  I provided a txt doc of the terminal.  
I should not have any issues with permissions so maybe there is something else wrong? 
Should be close but no cigar yet...Thanks for your help. 

I can try again on Monday.   

Talk later, 
Anthony-

Date: Tue, 7 Jul 2015 23:23:58 -0700
