### ISSUE TITLE
CDL with color decisions not exporting color corrects

### ISSUE THREAD

**Issue by gregcotten** [shidarin/cdl_convert#42]
running 
```
cdl_convert /path/to/reference.cdl -d ~/output 
```
The "reference .cdl" is the valid CDL in the tests. This results in 0 .cc files created but returns normally.

I suspect it is because parsing a CDL doesn't populate color_corrections - just color_decisions.

In the writing process in cdl_convert.py:
```python
# Writing
for ext in args.output:
    if ext in config.SINGLE_FORMATS or args.single:
        if filetype_in in config.COLLECTION_FORMATS:
            for color_correct in color_decisions.color_corrections:
                write_single_file(color_correct, ext)
```

Perhaps it should also iterate over the color_decisions and find their unique color corrections?

**Comment by gregcotten** [comment]
Maybe below "for color_correct in ..." we should add:

```python
from .collection import ColorCorrection
	for color_decision in color_decisions.color_decisions:
	    if(type(color_decision.cc) is ColorCorrection):
	        write_single_file(color_decision.cc, ext)
```

**Comment by shidarin** [comment]
Taking a look, I think the develop branch might have a fix for this already.

**Comment by shidarin** [comment]
Or not, since the develop branch is the same as master.

**Comment by shidarin** [comment]
Fixed in 52c91cd05f1f249fee08a4928ff030caebb75642

```python
            if ext in config.SINGLE_FORMATS or args.single:
                if filetype_in in config.COLLECTION_FORMATS:
                    for color_correct in color_decisions.color_corrections:
                        write_single_file(color_correct, ext)
                    for decision in color_decisions.color_decisions:
                        if decision.is_ref:
                            write_single_file(decision.cc.cc, ext)
                        else:
                            write_single_file(decision.cc, ext)
```

Also did the change to the sanity_check portion of the main run script.

Greg, as you probably saw, the current setup of that main() function is less than ideal. It looks like crap. Too many if/thens, the main() function is too long, etc etc. It needs to be torn apart. I've created [Issue 43](https://github.com/shidarin/cdl_convert/issues/43) to track that, but in the meantime I've added another iteration loop, matching the current coding style (terrible as it may be).

Hey, at least we avoid type checking? :)

Created [Issue 44](https://github.com/shidarin/cdl_convert/issues/44) to track updating tests for this issue.

**Comment by gregcotten** [comment]
I think you just shouldn't write out the references - just the ones that aren't references so you don't get duplicates!

**Comment by shidarin** [comment]
Good catch. We need to resolve references during python API usage, but not during the script itself.
